from .admin_handlers import admin_router

from .fallback_handler import fallback_router

from .user_commands_handlers import user_commands_router
from .user_menu_navigation_handlers import user_navigation_router
from .user_stats_handlers import user_stats_router
from .user_reminder_handlers import user_reminder_router
from .user_testing_handlers import user_testing_router
from .user_irr_verbs_handlers import user_irr_verbs_router
from .user_new_words_handlers import user_new_words_router
